---
name: armory-release

on:
  repository_dispatch:
    types: build-and-release

jobs:
  release-armory-docker:
    name: Build and release armory docker image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Build and release docker images
        run: |
          rm -rf /usr/share/dotnet &
          python -m pip install -r requirements.txt
          version=$(python -c "import armory; print(armory.__version__)")
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker pull twosixarmory/armory:latest
          bash docker/build.sh armory
          docker push twosixarmory/armory:${version}
          docker tag twosixarmory/armory:${version} twosixarmory/armory:latest
          docker push twosixarmory/armory:latest
  release-tf1-docker:
    name: Build and release tf1 docker image
    needs: [release-armory-docker]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
      - name: Build and release docker images
        run: |
          rm -rf /usr/share/dotnet &
          python -m pip install -r requirements.txt
          version=$(python -c "import armory; print(armory.__version__)")
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker pull twosixarmory/armory:${version}
          docker pull twosixarmory/tf1:latest
          bash docker/build.sh tf1
          docker push twosixarmory/tf1:${version}
          docker tag twosixarmory/tf1:${version} twosixarmory/tf1:latest
          docker push twosixarmory/tf1:latest
